#!/usr/bin/env bash

# 📊 ESTADO DE DESPLIEGUE - CrediPass en Monad Testnet
# Generated: 2026-06-06

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         ✅ CREDJPASS MONAD TESTNET - DESPLEGADO              ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 CONTRATOS DESPLEGADOS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🪙 MockMonad (Token para recompensas)"
echo "   Dirección: 0xB0207dD36D1441592aF6EC59dfC390B1f974615f"
echo "   Explorador: https://testnet.monadscan.com/address/0xB0207dD36D1441592aF6EC59dfC390B1f974615f"
echo ""

echo "🎫 CreditNFT (Pasaporte digital)"
echo "   Dirección: 0x67841E9cCa5bfd49A9102245277d6EdD5bCE8453"
echo "   Explorador: https://testnet.monadscan.com/address/0x67841E9cCa5bfd49A9102245277d6EdD5bCE8453"
echo ""

echo "🎁 RewardSystem (Sistema de recompensas)"
echo "   Dirección: 0xB59F9C7cdC9eF972c20ed9024cEEBe11820909FC"
echo "   Explorador: https://testnet.monadscan.com/address/0xB59F9C7cdC9eF972c20ed9024cEEBe11820909FC"
echo ""

echo "📡 CONFIGURACIÓN DE RED"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Red: Monad Testnet"
echo "Chain ID: 10143"
echo "RPC: https://testnet-rpc.monad.xyz"
echo "Explorador: https://testnet.monadscan.com"
echo ""

echo "⚙️ CONFIGURACIÓN DEL FRONTEND"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Variables de entorno configuradas en: frontend/.env.local"
echo ""
echo "NEXT_PUBLIC_MONAD_NFT_CONTRACT=0x67841E9cCa5bfd49A9102245277d6EdD5bCE8453"
echo "NEXT_PUBLIC_MONAD_REWARD_CONTRACT=0xB59F9C7cdC9eF972c20ed9024cEEBe11820909FC"
echo "NEXT_PUBLIC_MONAD_CCOP_CONTRACT=0xB0207dD36D1441592aF6EC59dfC390B1f974615f"
echo "NEXT_PUBLIC_MONAD_CHAIN_ID=10143"
echo ""

echo "🎮 MODO DEMO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Habilitado automáticamente cuando:"
echo "   - Usuario no conecta wallet, O"
echo "   - Usuario no tiene NFT minteado"
echo ""
echo "📊 Datos demo incluidos:"
echo "   • Score: 850 (Platino)"
echo "   • Pagos consecutivos: 5"
echo "   • Recompensas disponibles: 1,250 MON"
echo "   • Predicción IA"
echo "   • Historial de actividades"
echo ""

echo "🚀 PRÓXIMOS PASOS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Instalar dependencias del frontend:"
echo "   cd frontend && npm install"
echo ""
echo "2. Agregar Monad Testnet a MetaMask:"
echo "   - RPC: https://testnet-rpc.monad.xyz"
echo "   - Chain ID: 10143"
echo "   - Símbolo: MON"
echo ""
echo "3. Obtener tokens MON de faucet:"
echo "   https://faucet.monad.xyz"
echo ""
echo "4. Iniciar frontend:"
echo "   npm run dev"
echo ""
echo "5. Abrir en navegador:"
echo "   http://localhost:3000"
echo ""

echo "📖 DOCUMENTACIÓN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Ver archivos:"
echo "  • MONAD_CONFIG.md - Guía completa de configuración"
echo "  • INICIO_RAPIDO.md - Instrucciones rápidas"
echo "  • contracts/deployments/monad-testnet.json - Info de despliegue"
echo ""

echo "🎯 FUNCIONALIDADES DISPONIBLES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Conectar MetaMask"
echo "✅ Ver dashboard con datos demo"
echo "✅ Crear NFT de pasaporte"
echo "✅ Registrar pagos"
echo "✅ Recibir recompensas"
echo "✅ Ver predicciones IA"
echo "✅ Ranking de usuarios"
echo "✅ Historial de actividades"
echo ""

echo "⚠️ NOTAS IMPORTANTES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "• Los datos demo se muestran sin wallet conectado"
echo "• Los datos reales vienen de blockchain cuando hay NFT"
echo "• Necesitas MON tokens para gas (usa faucet)"
echo "• Todas las transacciones son en Monad Testnet"
echo "• Los datos persisten en blockchain (descentralizado)"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║    ✨ ¡Listo para usar! Abre http://localhost:3000             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
